# Generated by Django 3.2.6 on 2021-09-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='top_title',
            field=models.CharField(default=1, max_length=100, verbose_name='TOPページタイトル'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='author',
            field=models.CharField(max_length=30, verbose_name='管理者'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='meta_keywords',
            field=models.CharField(max_length=300, verbose_name='SEOキーワード'),
        ),
    ]
